### ISSUE TITLE
Bing translate error

### ISSUE THREAD

**Issue by viggo-lee** [dmytrovoytko/SublimeText-Translate#3]
<img width="352" alt="image" src="https://github.com/dmytrovoytko/SublimeText-Translate/assets/9639542/dbf30132-a739-4aa7-8cc0-6fd7c0dd6020">

config:
```json
{
  "engine": "bing",
  "source_language": "",
  "target_language": "zh-Hans",
  "results_mode": "to_buffer",
  "show_popup": true,
  "replace_linebreaks": false,
  "linebreak_replacement": " ",
  "analysis_language": "zh-Hans"
}
```
error:
`Bing translate error: No JSON object could be decoded`

**Comment by dmytrovoytko** [comment]
Thank you for using my plugin and writing this request.

1. Can you please provide the exact text you're trying to translate so I could try to reproduce the situation?

2. Does it work for you with the same settings on any other simple English text?
(to understand if it's a problem with firewall or network access)
Please insert "testing sentence" into your sublime text editor and try to translate it.

**Comment by viggo-lee** [comment]
<img width="766" alt="image" src="https://github.com/dmytrovoytko/SublimeText-Translate/assets/9639542/29de630e-9ea0-45e4-b06b-76836c067ff4">

1. firewall is disable
2. translate the "testing sentence" is fail
3. the error message "Bing translate error: No JSON object could be decoded" in console 

<img width="1698" alt="image" src="https://github.com/dmytrovoytko/SublimeText-Translate/assets/9639542/f75489d2-7e80-4a0b-9629-c5e427cf6d83">

1. i use [bing's translation](https://cn.bing.com/translator?ref=TThis&text=&from=en&to=zh-Hans) is normal

**Comment by dmytrovoytko** [comment]
Thank you for these details.
I'm preparing a testing build to use cn.bing.com

It doesn't work from my country, so it needs to be tested from China.

Please let me know if you have python on your computer and ready to test a beta version.

**Comment by dmytrovoytko** [comment]
And by the way, did you try using Google or googlehk engine in plugin settings? Does that translation work for you?

**Comment by viggo-lee** [comment]
> Thank you for these details. I'm preparing a testing build to use cn.bing.com
> 
> It doesn't work from my country, so it needs to be tested from China.
> 
> Please let me know if you have python on your computer and ready to test a beta version.



> And by the way, did you try using Google or googlehk engine in plugin settings? Does that translation work for you?

1. my os is macos(m3 apple silicon), and local python ver is 3.11.7
2. access to google.com or google.hk is not allow in china
3. access to bing.com is allow in china

**Comment by dmytrovoytko** [comment]
Good!
Let's try cn.bing then!

Please download this test version
https://raw.githubusercontent.com/dmytrovoytko/SublimeText-Translate/bingcn-test/Translator.py

And then just run
python Translator.py 
in your terminal opened in the folder with the downloaded file (or use full path to it)
Ah, maybe it's ‘python3‘ for you.

Finally send the output to the comments here.

**Comment by viggo-lee** [comment]
> Good! Let's try cn.bing then!
> 
> Please download this test version https://raw.githubusercontent.com/dmytrovoytko/SublimeText-Translate/bingcn-test/Translator.py
> 
> And then just run python Translator.py in your terminal opened in the folder with the downloaded file (or use full path to it) Ah, maybe it's ‘python3‘ for you.
> 
> Finally send the output to the comments here.

<img width="1100" alt="image" src="https://github.com/dmytrovoytko/SublimeText-Translate/assets/9639542/cf0230ce-40fa-4959-b87d-2002fbef227b">

**1. console message in red tag 1 : by raw python file `Translator.py` print out**
**2. console message in red tag 2 : by i insert python code into `Translator.py` file print out, i add python code see image:**

<img width="2060" alt="image" src="https://github.com/dmytrovoytko/SublimeText-Translate/assets/9639542/294b9a4d-ddee-4378-a51d-6e1ad3d84784">

**Comment by dmytrovoytko** [comment]
Ah, right, you need another file
Please download also https://raw.githubusercontent.com/dmytrovoytko/SublimeText-Translate/bingcn-test/bing_languages.json

Save it to the same folder, and then run

python Translator.py
in your terminal opened in the folder with the downloaded files.

Finally send the output to the comments here.

**Comment by dmytrovoytko** [comment]
I just released a new version (3.3.1) of plugin. Sublime text should update it automatically when you (re)start it.
Please change engine in settings after update: 'bing' to 'bingcn'
and try translating. Please report me your results as I can't test it fully from outside of China.  Thank you!

**Comment by viggo-lee** [comment]
> I just released a new version (3.3.1) of plugin. Sublime text should update it automatically when you (re)start it. Please change engine in settings after update: 'bing' to 'bingcn' and try translating. Please report me your results as I can't test it fully from outside of China. Thank you!

thx, it work whit cn.bing.com

<img width="2056" alt="image" src="https://github.com/dmytrovoytko/SublimeText-Translate/assets/9639542/299a9985-4914-4bb4-ae65-67978dd28f72">

**Comment by dmytrovoytko** [comment]
So glad it finally works for you! Thank you for patience and testing!
Please ⭐️star⭐️ my repo https://github.com/dmytrovoytko/SublimeText-Translate/ to help other people discover it 🙏

**Comment by viggo-lee** [comment]
> So glad it finally works for you! Thank you for patience and testing! Please ⭐️star⭐️ my repo https://github.com/dmytrovoytko/SublimeText-Translate/ to help other people discover it 🙏

thx
